import type { Metadata } from 'next'
import Link from 'next/link'
import { PageHero } from '@/components/page-hero'

export const metadata: Metadata = { title: 'Metodologia do Registro de Demandas', description: 'Conheça os critérios para organizar relatos comunitários em manifestações claras, responsáveis e revisadas por pessoas.', alternates: { canonical: '/metodologia' } }
const steps = [['1','Relato popular','A pessoa descreve a situação com suas próprias palavras.'],['2','Identificação','A ferramenta organiza localidade, tema e tipo de manifestação.'],['3','Conversão técnica','O relato vira uma minuta clara, sem alterar seu sentido.'],['4','Revisão humana','O cidadão confere nomes, fatos, datas e o pedido formulado.'],['5','Encaminhamento','A minuta é levada ao canal oficial competente.'],['6','Controle social','Protocolo e resposta podem ser acompanhados pelo cidadão.']]
export default function MetodologiaPage() {
  return <main><PageHero eyebrow="Como funciona" title="Metodologia do Registro de Demandas" description="Critérios para transformar linguagem cotidiana em participação cidadã responsável, sem apagar a voz de quem relata." /><section className="mx-auto max-w-6xl px-4 py-12"><div className="grid gap-4 md:grid-cols-3">{steps.map(([n,t,d]) => <article key={n} className="rounded-2xl border bg-card p-6"><span className="font-serif text-3xl text-accent">{n}</span><h2 className="mt-3 font-serif text-xl font-semibold">{t}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{d}</p></article>)}</div><div className="mt-10 grid gap-6 md:grid-cols-2"><article className="rounded-2xl bg-primary p-7 text-primary-foreground"><h2 className="font-serif text-2xl font-semibold">O apoio automatizado pode</h2><ul className="mt-4 space-y-2 text-sm">{['Organizar informações e melhorar a redação','Identificar temas e sugerir perguntas','Produzir uma minuta editável','Facilitar linguagem e sistematização'].map((x) => <li key={x}>✓ {x}</li>)}</ul></article><article className="rounded-2xl border bg-card p-7"><h2 className="font-serif text-2xl font-semibold">O apoio automatizado não pode</h2><ul className="mt-4 space-y-2 text-sm text-muted-foreground">{['Comprovar fatos ou decidir quem tem razão','Substituir órgãos públicos ou assessoria jurídica','Protocolar ou garantir uma solução','Dispensar revisão e responsabilidade humana'].map((x) => <li key={x}>× {x}</li>)}</ul></article></div><div className="mt-10 rounded-2xl border-l-4 border-accent bg-secondary/50 p-7"><h2 className="font-serif text-2xl font-semibold">Compromissos metodológicos</h2><p className="mt-3 leading-relaxed text-muted-foreground">Transparência sobre o uso da ferramenta, finalidade clara, minimização de dados, proteção de informações sensíveis, neutralidade partidária, indicação de fontes e revisão humana em todas as situações.</p><Link href="/demandas" className="mt-5 inline-flex rounded-full bg-primary px-5 py-3 font-semibold text-primary-foreground">Usar o Registro de Demandas</Link></div></section></main>
}
